kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: packet-example-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "packet-example-class"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
